import { describe, it, expect, jest, beforeEach } from "@jest/globals";
import type { AiModelProvider, ModelResponse } from "@oracle69/sales-intelligence";
import { HrAiService } from "../services/hr-ai.service.js";
import { createHrTestModule, HrTestContext } from "../testing/test-fixture.js";
import { EmployeeStatus, HrHealth } from "../types.js";

function sampleHealth(kpis: Partial<HrHealth["kpis"]> = {}): HrHealth {
  return {
    score: 85,
    status: "healthy",
    openPositions: 0,
    candidatesInPipeline: 0,
    reasoning: ["The workforce is stable."],
    kpis: {
      headcount: 5,
      activeHeadcount: 4,
      onboardingCount: 1,
      offboardingCount: 0,
      turnoverCount: 0,
      turnoverRate: 0,
      openPositions: 0,
      filledPositions: 1,
      candidatesInPipeline: 0,
      hiredCandidates: 1,
      offerAcceptanceRate: 0.5,
      averageTimeToHireDays: 20,
      ...kpis,
    },
  };
}

function mockProvider(response: string): AiModelProvider {
  return {
    name: "mock",
    analyze: jest.fn().mockResolvedValue({ content: response } as ModelResponse),
    generate: jest.fn().mockResolvedValue({ content: response } as ModelResponse),
  };
}

describe("HR AI insights", () => {
  let ctx: HrTestContext;

  beforeEach(() => {
    ctx = createHrTestModule();
    delete process.env.GOOGLE_AI_API_KEY;
  });

  it("should generate deterministic insights for a healthy workforce without an AI provider", async () => {
    const health = sampleHealth();
    const insights = await ctx.aiService.generateInsights(health);

    expect(insights.length).toBeGreaterThanOrEqual(3);
    expect(insights.every((i) => typeof i.content === "string" && i.content.length > 0)).toBe(true);
  });

  it("should alert on an empty workforce", async () => {
    const insights = await ctx.aiService.generateInsights(
      sampleHealth({ headcount: 0, activeHeadcount: 0, onboardingCount: 0 }),
    );
    expect(insights.some((i) => i.type === "alert" && i.title === "Empty Workforce")).toBe(true);
  });

  it("should alert on elevated turnover", async () => {
    const insights = await ctx.aiService.generateInsights(
      sampleHealth({ turnoverRate: 0.3, turnoverCount: 2 }),
    );
    expect(insights.some((i) => i.type === "alert" && i.title === "Elevated Turnover")).toBe(true);
  });

  it("should alert on a recruitment pipeline gap", async () => {
    const insights = await ctx.aiService.generateInsights(
      sampleHealth({ openPositions: 3, candidatesInPipeline: 1 }),
    );
    expect(insights.some((i) => i.title === "Recruitment Pipeline Gap")).toBe(true);
  });

  it("should use AI output when a provider is configured", async () => {
    process.env.GOOGLE_AI_API_KEY = "test-key";
    const provider = mockProvider(
      JSON.stringify([
        {
          type: "alert",
          title: "AI Insight",
          content: "Generated by the model.",
          priority: "high",
          impact: "AI",
        },
      ]),
    );
    const aiService = new HrAiService(provider);

    const insights = await aiService.generateInsights(sampleHealth());
    expect(insights).toHaveLength(1);
    expect(insights[0]).toMatchObject({ title: "AI Insight", content: "Generated by the model." });
  });

  it("should fall back to deterministic insights when the AI call fails", async () => {
    process.env.GOOGLE_AI_API_KEY = "test-key";
    const provider: AiModelProvider = {
      name: "mock",
      analyze: jest.fn().mockRejectedValue(new Error("boom")) as any,
      generate: jest.fn() as any,
    };
    const aiService = new HrAiService(provider);

    const insights = await aiService.generateInsights(sampleHealth());
    expect(insights.length).toBeGreaterThanOrEqual(3);
    expect(insights.every((i) => typeof i.content === "string")).toBe(true);
  });

  it("should fall back when the AI returns unusable JSON", async () => {
    process.env.GOOGLE_AI_API_KEY = "test-key";
    const provider = mockProvider("not-json-at-all");
    const aiService = new HrAiService(provider);

    const insights = await aiService.generateInsights(sampleHealth());
    expect(insights.length).toBeGreaterThanOrEqual(3);
  });
});
